name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: step 1 - create temporary artifact downloads folder 
      run: mkdir downloads
    - name: step2 - Add artifacts to publish to the temp folder 
      run: |
          cd downloads
          echo 'alpha' > alpha.html
          echo 'beta'  > beta.html
          echo 'gamma' > gamma.html
          cd ..
    - name: step 3 - use the upload artifact github action
      uses: actions/upload-artifact@v2
      with:
            name: assets-for-download
            path: downloads
  
